use_frameworks!

target 'HActionButton_Example' do
  pod 'HActionButton', :path => '../'

  target 'HActionButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9.0’
  pod 'Nimble', '~> 4.0’
  end
end
