use_frameworks!

target 'HActionButton_Example' do
  pod 'HActionButton', :path => '../'

  target 'HActionButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
